version: '3'
services:
  app:
      build: 
        context: .
        args:
          - var1=admin
          - var2=password
      ports:
        - "5600:5600"
  mongodb:
      image: mongo
      ports:
        - 27017:27017
      # environment:
      #   - MONGO_INITDB_ROOT_USERNAME=admin
      #   - MONGO_INITDB_ROOT_PASSWORD=password 
      volumes:
        - mongo-data:/data/db 
volumes:
  mongo-data:
    driver: local 
